[tools]
python = "3.12"
uv = "latest"
node = "latest"

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"


[tasks.install]
description = "Install dependencies"
alias = "i"
dir = "backend"
run = "uv sync"

[tasks.serve]
description = "Run local server"
alias = "s"
dir = "backend"
run = "uv run uvicorn main:app --host 0.0.0.0 --port 8000"

