"""add registration_deadline to activities

Revision ID: 45194504f058
Revises: 647a9d141b83
Create Date: 2026-05-09 01:35:41.919442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45194504f058'
down_revision: Union[str, Sequence[str], None] = '647a9d141b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('registration_deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'registration_deadline')
    # ### end Alembic commands ###
