"""add schedule fields to activities

Revision ID: 4f6df96a0fb9
Revises: f8c66e4e677b
Create Date: 2026-05-09 12:45:07.505173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6df96a0fb9'
down_revision: Union[str, Sequence[str], None] = 'f8c66e4e677b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('activities', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'end_time')
    op.drop_column('activities', 'start_time')
    op.drop_column('activities', 'day_of_week')
    # ### end Alembic commands ###
