"""add telephone to adhesions

Revision ID: f8c66e4e677b
Revises: 45194504f058
Create Date: 2026-05-09 01:39:01.889958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c66e4e677b'
down_revision: Union[str, Sequence[str], None] = '45194504f058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adhesions', sa.Column('telephone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adhesions', 'telephone')
    # ### end Alembic commands ###
