"""add discount fields to adhesions

Revision ID: fae29ada105d
Revises: 4f6df96a0fb9
Create Date: 2026-05-09 21:45:48.758121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae29ada105d'
down_revision: Union[str, Sequence[str], None] = '4f6df96a0fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adhesions', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('adhesions', sa.Column('discount_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adhesions', 'discount_reason')
    op.drop_column('adhesions', 'discount_amount')
    # ### end Alembic commands ###
